name: deploy
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: 'Java env'
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '8'
        server-id: maven
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - run: mvn -B deploy -Dgpg.skip
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USER_NAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

