name: maven deploy
on:
  push:
    branches:
      - dev
      - release
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Java Environment
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
          server-id: maven
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          settings-path: ${{ github.action_path }}
      - name: echo
        run: ls $GITHUB_ACTION_PATH && pwd
      - name: Publish Maven
        run: mvn deploy -Dmaven.test.skip=true -s $GITHUB_WORKSPACE/settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USER_NAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
