name: Gitee repos mirror periodic job
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v1
    - name: Get Git Log
      id: git_log
      uses: JantHsueh/get-git-log-action@master
      with:
        tag: master
