name: Gitee repos mirror periodic job
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v1
    - name: Get Git Log
      id: git_log
      uses: Edisonboy/latest-git-log-action@main
      with:
        tag: origin/master
    - name: 'echo'
      run: echo $log
    - name: Send email
      uses: devellany/send-mailer@v1.0.2
      with:
        host: smtp.qq.com
        account: ${{secrets.ACCOUNT}}
        password: ${{secrets.MAIL_PASSWORD}}
        sender: edison
        from: ${{secrets.MAIL_ADDRESS}}
        to: edisonzhang5200@gmail.com
        subject: mail title.
        body: message test
